- name: exzample
  gather_facts: false
  hosts: [all]

  tasks:

    - name: Create conteiner
      docker_container:
        name: indexwork
        image: iko90/indexwork
        pull: true
        state: started
        ports:
          - "80:80"